import logging
import os
from datetime import datetime
from app.agents.base import BaseAgent
from app.db.store import tasks_store, memory_store
from app.slack.client import slack_client
from app.github.client import github_client
from app.config import settings

logger = logging.getLogger("forgeos.developer")


class DeveloperAgent(BaseAgent):
    def __init__(self):
        super().__init__(name="Developer Agent", role="Code Implementation and Modification")

    async def execute_task(self, task_id: str) -> bool:
        tasks = tasks_store.read_all()
        task = tasks.get(task_id)
        if not task:
            logger.error(f"Task {task_id} not found.")
            return False

        logger.info(
            "\n"
            "──────────────────────────────\n"
            "Invoking: Developer Agent\n"
            "Reason:   Implementation Task\n"
            f"  Task ID: {task_id}\n"
            f"  Task:    {task['title']}\n"
            f"  Model:   {task['model']}\n"
            "──────────────────────────────"
        )
        slack_client.log_event("Developer", "Task Started", task["title"], task_id)

        await slack_client.post_message(
            "#agent-developer",
            f"🚀 *Task Started*: Developer Agent implementing \"{task['title']}\" with `{task['model']}`.",
        )
        await slack_client.post_message(
            "#sprint-main",
            f"💻 *Coding Started*: Developer Agent writing implementation for \"{task['title']}\".",
        )

        task["status"] = "In Progress"
        task["assigned_agent"] = "Developer Agent"
        tasks[task_id] = task
        tasks_store.write_all(tasks)

        # Build system prompt with injected skill rules
        from app.skills.engine import skill_engine
        task_skills = task.get("skills", ["fastapi", "backend"])
        injected_skills_prompt = skill_engine.get_injected_prompt(task_skills)
        system_prompt = (
            "You are the Lead Developer Agent of ForgeOS. Write clean, maintainable, "
            "production-grade Python/FastAPI code with proper typing and async structures."
            f"{injected_skills_prompt}"
        )
        prompt = f"Implement: {task['title']} — {task['description']}. Provide the code structure."
        code_response = await self.call_llm(prompt, system_prompt, task["model"])

        # Write implementation file via OpenClaw simulation
        out_dir = os.path.join(
            os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "demo"
        )
        os.makedirs(out_dir, exist_ok=True)
        demo_code_path = os.path.join(out_dir, "fastapi_crud.py")
        try:
            with open(demo_code_path, "w") as f:
                f.write(f"# Generated by ForgeOS Developer Agent via OpenClaw\n# {datetime.utcnow()}\n\n")
                f.write("from fastapi import FastAPI, HTTPException\nfrom pydantic import BaseModel\n\n")
                f.write('app = FastAPI(title="ForgeOS CRUD API")\n\n')
                f.write("class Item(BaseModel):\n    id: int\n    name: str\n    description: str\n\n")
                f.write("database: dict = {}\n\n")
                f.write('@app.post("/items/", response_model=Item)\nasync def create_item(item: Item):\n')
                f.write("    if item.id in database:\n        raise HTTPException(status_code=400, detail=\"Exists\")\n")
                f.write("    database[item.id] = item\n    return item\n\n")
                f.write('@app.get("/items/{item_id}", response_model=Item)\nasync def read_item(item_id: int):\n')
                f.write("    if item_id not in database:\n        raise HTTPException(status_code=404, detail=\"Not found\")\n")
                f.write("    return database[item_id]\n")
            slack_client.log_event("Developer", "Code Written", f"OpenClaw wrote {demo_code_path}", task_id)
            logger.info(f"OpenClaw wrote implementation to {demo_code_path}")
        except Exception as e:
            logger.error(f"OpenClaw write failed: {e}")
            slack_client.log_event("Developer", "OpenClaw Error", str(e), task_id)

        # Git commit + PR
        git_success = await github_client.create_commit(
            branch="feature/fastapi-crud",
            commit_message=f"feat: implement {task['title'].lower()}",
            files_changed=[demo_code_path],
        )
        if git_success:
            slack_client.log_event("Git", "Commit Created", f"feat: implement {task['title'].lower()}", task_id)
            await slack_client.post_message(
                "#agent-developer",
                f"📦 *Git Commit*: Committed to branch `feature/fastapi-crud`.\n`feat: implement {task['title'].lower()}`",
            )
            pr_data = await github_client.create_pull_request(
                title=f"feat: implement {task['title'].lower()}",
                body=f"Implements task {task_id}: {task['description']}",
                head_branch="feature/fastapi-crud",
                base_branch="main",
            )
            slack_client.log_event("Git", "PR Opened", f"PR #{pr_data['id']}: {pr_data['title']}", task_id)
            await slack_client.post_message(
                "#sprint-main",
                f"🔀 *PR Opened*: PR #{pr_data['id']} \"{pr_data['title']}\"\n{pr_data['url']}",
            )
            await slack_client.post_message(
                "#ci-cd",
                "🔄 *CI Started*: GitHub Actions triggered for `feature/fastapi-crud`.",
            )
            slack_client.log_event("CI", "Started", "GitHub Actions triggered.", task_id)

        task["status"] = "Review"
        tasks[task_id] = task
        tasks_store.write_all(tasks)

        await slack_client.post_message(
            "#agent-developer",
            f"✅ *Implementation Complete*: \"{task['title']}\" moved to Review.",
        )
        slack_client.log_event("Developer", "Task Complete", f"Moved to Review", task_id)
        return True


developer_agent = DeveloperAgent()
